# Generated by Django 4.1 on 2022-08-16 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_form_edonator_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donor_form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=122)),
                ('address1', models.CharField(max_length=122)),
                ('address2', models.CharField(max_length=122)),
                ('district', models.CharField(max_length=122)),
                ('city', models.CharField(max_length=122)),
                ('state', models.CharField(max_length=122)),
                ('pincode', models.CharField(max_length=122)),
                ('Contact_no', models.CharField(max_length=12)),
                ('size', models.CharField(max_length=122)),
                ('quantity', models.CharField(max_length=122)),
                ('date_s', models.CharField(max_length=122)),
                ('time', models.CharField(max_length=122)),
                ('e_img', models.FileField(upload_to='')),
                ('date', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='Form_edonator',
        ),
    ]
