# Generated by Django 4.1 on 2022-08-20 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_donor_form_delete_form_edonator'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donor_form',
            old_name='Contact_no',
            new_name='contact_no',
        ),
    ]
